test_config: &test_config
  volume: php:/tmp
  cmd:
    - php --version
    - composer --version
    - modd --version
    - php-cs-fixer --version
    - security-checker -help
    - php /tmp/test.php

build_args: &build_args
  APCU_VERSION: 5.1.22
  COMPOSER_VERSION: 2.5.1
  ICONV_VERSION: 1.15-r3
  MEMCACHED_VERSION: 3.2.0
  MODD_VERSION: *MODD_VERSION
  PHP_CS_FIXER_VERSION: 3.13.2
  REDIS_VERSION: 5.3.7
  SECURITY_CHECKER_VERSION: 2.0.6
  XDEBUG_VERSION: 3.2.0

versions:
  "8.0":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      <<: *build_args
      MUSL_VERSION: 1.2.2-r7
    test_config: *test_config
  "8.1":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      <<: *build_args
      MUSL_VERSION: 1.2.3-r4
    test_config: *test_config
  "8.2":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      <<: *build_args
      MUSL_VERSION: 1.2.3-r4
    test_config: *test_config
